### ISSUE TITLE
"Become a Fanatic" workflow fails due to timeout while trying to capture progress

### ISSUE THREAD

**Issue by Adamouization** [connorads/stackoverflow-fanatic#36]
Hi, as the title says, the workflow fails at the "User does not have Fanatic badge yet so capture progress" step. Ran the "Tests" workflow first and this works fine. Unsure what could be causing the issue though, just wanted to flag it.

Here's the full Traceback:

```
Run npm start
  

> stackoverflow-fanatic@0.0.1 prestart /home/runner/work/Stackoverflow-Fanatic-Badge/Stackoverflow-Fanatic-Badge
> npm run compile


> stackoverflow-fanatic@0.0.1 compile /home/runner/work/Stackoverflow-Fanatic-Badge/Stackoverflow-Fanatic-Badge
> tsc


> stackoverflow-fanatic@0.0.1 start /home/runner/work/Stackoverflow-Fanatic-Badge/Stackoverflow-Fanatic-Badge
> node --unhandled-rejections=strict build/src/index.js

Go to badges page
url https://stackoverflow.com/help/badges
Try to click badge: fanatic
url https://stackoverflow.com/help/badges/[8](https://github.com/Adamouization/Stackoverflow-Fanatic-Badge/actions/runs/3883995362/jobs/6625968008#step:5:8)3/fanatic
Got badge number [ 'fanatic', 83 ]
Login to https://stackoverflow.com/
url https://stackoverflow.com/users/login
Go to profile
url https://stackoverflow.com/
Go to user's Fanatic badge page
url https://stackoverflow.com/users/560[9](https://github.com/Adamouization/Stackoverflow-Fanatic-Badge/actions/runs/3883995362/jobs/6625968008#step:5:10)328/adam-jaamour
userid 5609328
Has the user been awarded the Fanatic badge yet?
url https://stackoverflow.com/help/badges/83/?userid=5609328
Fanatic awarded? No
Screenshot saved { path: 'awarded.png' }
User does not have Fanatic badge yet so capture progress
url https://stackoverflow.com/users/5609328/adam-jaamour
internal/process/promises.js:213
        triggerUncaughtException(err, true /* fromPromise */);
        ^

page.waitForSelector: Timeout 30000ms exceeded.
=========================== logs ===========================
waiting for selector "[data-badge-database-name="Fanatic"]" to be visible
============================================================
Note: use DEBUG=pw:api environment variable and rerun to capture Playwright logs.
    at Connection.sendMessageToServer (/home/runner/work/Stackoverflow-Fanatic-Badge/Stackoverflow-Fanatic-Badge/node_modules/playwright/lib/client/connection.js:69:15)
    at Proxy.<anonymous> (/home/runner/work/Stackoverflow-Fanatic-Badge/Stackoverflow-Fanatic-Badge/node_modules/playwright/lib/client/channelOwner.js:44:61)
    at /home/runner/work/Stackoverflow-Fanatic-Badge/Stackoverflow-Fanatic-Badge/node_modules/playwright/lib/client/frame.js:180:48
    at Frame._wrapApiCall (/home/runner/work/Stackoverflow-Fanatic-Badge/Stackoverflow-Fanatic-Badge/node_modules/playwright/lib/client/channelOwner.js:72:34)
    at Frame.waitForSelector (/home/runner/work/Stackoverflow-Fanatic-Badge/Stackoverflow-Fanatic-Badge/node_modules/playwright/lib/client/frame.js:175:21)
    at /home/runner/work/Stackoverflow-Fanatic-Badge/Stackoverflow-Fanatic-Badge/node_modules/playwright/lib/client/page.js:215:60
    at Page._attributeToPage (/home/runner/work/Stackoverflow-Fanatic-Badge/Stackoverflow-Fanatic-Badge/node_modules/playwright/lib/client/page.js:205:20)
    at Page.waitForSelector (/home/runner/work/Stackoverflow-Fanatic-Badge/Stackoverflow-Fanatic-Badge/node_modules/playwright/lib/client/page.js:215:21)
    at /home/runner/work/Stackoverflow-Fanatic-Badge/Stackoverflow-Fanatic-Badge/build/src/index.js:44:20 {
  name: 'TimeoutError'
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! stackoverflow-fanatic@0.0.1 start: `node --unhandled-rejections=strict build/src/index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the stackoverflow-fanatic@0.0.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runner/.npm/_logs/2023-01-[10](https://github.com/Adamouization/Stackoverflow-Fanatic-Badge/actions/runs/3883995362/jobs/6625968008#step:5:11)T13_55_[34](https://github.com/Adamouization/Stackoverflow-Fanatic-Badge/actions/runs/3883995362/jobs/6625968008#step:5:35)_[57](https://github.com/Adamouization/Stackoverflow-Fanatic-Badge/actions/runs/3883995362/jobs/6625968008#step:5:58)0Z-debug.log
Error: Process completed with exit code 1.
```

**Comment by bugbounted** [comment]
same problem ...

**Comment by connorads** [comment]
Hi @bugbounted, I was unable to reproduce as per my previous comment so if you can give reproduction steps I'll take a look.

**Comment by jmevel** [comment]
Hello,

Same issue here, I just cloned the repo, created the secrets and I the exact same timeout as Adam.

There's no other steps besides running this Action with an account which does NOT yet have the fanatic badge.
